[package]
edition.workspace = true
name = "introspect-type-library"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
introspect-types = { path = "../types" }
[dev-dependencies]
