// pub mod example_gen;
pub mod deref;
pub mod example_use;
pub mod gen_groups;
pub mod gen_table_id;
pub mod gen_table_keyed;
pub mod gen_table_no_id;
// mod exmaple_contract;
pub mod table;
pub use deref::{Snapable, Spannable};
